In [1]:
#Importing the excel file we converted in step 1
import pandas as pd
df1 = pd.read_csv("C:\\Users\\Akanksha\\Desktop\\czi\\10194-red.csv",error_bad_lines=False,header=None)
df1

,0,1,2,3,4,5,6,7,8,9,...,242,243,244,245,246,247,248,249,250,251
0,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
1,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
2,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
3,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
4,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
336,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
337,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
338,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
339,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255

In [4]:
#Checking summary of elements
df_desc = df1.describe()
df_desc

,0,1,2,3,4,5,6,7,8,9,...,242,243,244,245,246,247,248,249,250,251
count,340.0,340.0,340.0,340.0,340.0,340.0,340.0,340.000000,340.000000,340.000000,...,340.00000,340.000000,340.0,340.0,340.0,340.0,340.0,340.0,340.0,340.0
mean,255.0,255.0,255.0,255.0,255.0,255.0,255.0,252.000000,250.500000,252.000000,...,188.25000,183.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.535978,33.624027,27.535978,...,112.26199,114.955936,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,255.0,255.0,255.0,255.0,255.0,255.0,255.0,0.000000,0.000000,0.000000,...,0.00000,0.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
25%,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.000000,255.000000,255.000000,...,0.00000,0.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
50%,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.000000,255.000000,255.000000,...,255.00000,255.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
75%,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.000000,255.000000,255.000000,...,255.00000,255.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
max,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.000000,255.000000,255.000000,...,255.00000,255.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0

In [16]:
#Saving summary stats as excel to view easily
df_desc.to_excel("C://Users//Akanksha//Desktop//czi//10194-red-stats.xlsx")

In [5]:
#Repeating same steps for second image. 
import pandas as pd
df2 = pd.read_csv("C:\\Users\\Akanksha\\Desktop\\czi\\10188-red-csv.csv",index_col=0)
df2

,0,1,2,3,4,5,6,7,8,9,...,242,243,244,245,246,247,248,249,250,251
i,,,,,,,,,,,,,,,,,,,,,
0,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
1,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
2,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
3,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
4,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
336,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
337,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
338,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
339,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255

In [7]:
#Saving summary stats 
df_desc2 = df1.describe()
df_desc2

,0,1,2,3,4,5,6,7,8,9,...,242,243,244,245,246,247,248,249,250,251
count,340.0,340.0,340.0,340.0,340.0,340.0,340.0,340.000000,340.000000,340.000000,...,340.00000,340.000000,340.0,340.0,340.0,340.0,340.0,340.0,340.0,340.0
mean,255.0,255.0,255.0,255.0,255.0,255.0,255.0,252.000000,250.500000,252.000000,...,188.25000,183.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.535978,33.624027,27.535978,...,112.26199,114.955936,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,255.0,255.0,255.0,255.0,255.0,255.0,255.0,0.000000,0.000000,0.000000,...,0.00000,0.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
25%,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.000000,255.000000,255.000000,...,0.00000,0.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
50%,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.000000,255.000000,255.000000,...,255.00000,255.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
75%,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.000000,255.000000,255.000000,...,255.00000,255.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
max,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.000000,255.000000,255.000000,...,255.00000,255.000000,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0

In [28]:
df_desc2.to_excel("C://Users//Akanksha//Desktop//czi//10188-red-stats.xlsx")

In [35]:
#Repeating same steps for third image. 
import pandas as pd
df1 = pd.read_csv("C:\\Users\\Akanksha\\Desktop\\czi\\10192-red-csv.csv",index_col=0)
df1

,0,1,2,3,4,5,6,7,8,9,...,242,243,244,245,246,247,248,249,250,251
i,,,,,,,,,,,,,,,,,,,,,
0,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
1,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
2,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
3,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
4,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
336,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
337,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
338,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
339,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255

In [36]:
df_desc = df1.describe()

In [37]:
df_desc.to_excel("C://Users//Akanksha//Desktop//czi//10192-red-stats.xlsx")